[package]
name = "hypo"
version = "0.1.0"
edition = "2024"

license = "MPL-2.0"
categories = ["template-engine"]
keywords = ["html", "markup", "template", "hypertext"]
description = "tiny crate that renders html through macros"

documentation = "https://docs.rs/hypo"
repository = "https://github.com/lsunsi/hypo"

[features]
perf = ["dep:itoap"]
kebab = ["dep:const-str"]

[dependencies]
const-str = { version = "1.0.0", default-features = false, optional = true }
itoap = { version = "1.0.1", default-features = false, features = ["alloc"], optional = true }

[dev-dependencies]
maud = { version = "0.27.0", default-features = false }
